// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPasswordService creates a new instance of MockPasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordService {
	mock := &MockPasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordService is an autogenerated mock type for the PasswordService type
type MockPasswordService struct {
	mock.Mock
}

type MockPasswordService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordService) EXPECT() *MockPasswordService_Expecter {
	return &MockPasswordService_Expecter{mock: &_m.Mock}
}

// ComparePasswords provides a mock function for the type MockPasswordService
func (_mock *MockPasswordService) ComparePasswords(hashedPassword string, plaintextPassword string) error {
	ret := _mock.Called(hashedPassword, plaintextPassword)

	if len(ret) == 0 {
		panic("no return value specified for ComparePasswords")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(hashedPassword, plaintextPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPasswordService_ComparePasswords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComparePasswords'
type MockPasswordService_ComparePasswords_Call struct {
	*mock.Call
}

// ComparePasswords is a helper method to define mock.On call
//   - hashedPassword
//   - plaintextPassword
func (_e *MockPasswordService_Expecter) ComparePasswords(hashedPassword interface{}, plaintextPassword interface{}) *MockPasswordService_ComparePasswords_Call {
	return &MockPasswordService_ComparePasswords_Call{Call: _e.mock.On("ComparePasswords", hashedPassword, plaintextPassword)}
}

func (_c *MockPasswordService_ComparePasswords_Call) Run(run func(hashedPassword string, plaintextPassword string)) *MockPasswordService_ComparePasswords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordService_ComparePasswords_Call) Return(err error) *MockPasswordService_ComparePasswords_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPasswordService_ComparePasswords_Call) RunAndReturn(run func(hashedPassword string, plaintextPassword string) error) *MockPasswordService_ComparePasswords_Call {
	_c.Call.Return(run)
	return _c
}

// HashPassword provides a mock function for the type MockPasswordService
func (_mock *MockPasswordService) HashPassword(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordService_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type MockPasswordService_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password
func (_e *MockPasswordService_Expecter) HashPassword(password interface{}) *MockPasswordService_HashPassword_Call {
	return &MockPasswordService_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *MockPasswordService_HashPassword_Call) Run(run func(password string)) *MockPasswordService_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPasswordService_HashPassword_Call) Return(s string, err error) *MockPasswordService_HashPassword_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPasswordService_HashPassword_Call) RunAndReturn(run func(password string) (string, error)) *MockPasswordService_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}
